# Generated by Django 3.2.5 on 2021-07-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('actor_surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('actor_patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_title', models.CharField(max_length=50, verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('producer_id', models.AutoField(primary_key=True, serialize=False)),
                ('producer_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('producer_surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('producer_patronymic', models.CharField(max_length=100, null=True, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=150, verbose_name='Название фильма')),
                ('movie_description', models.TextField(verbose_name='Описание фильма')),
                ('movie_trailer', models.TextField(verbose_name='Ссылка на трейлер')),
                ('movie_mark', models.IntegerField(default=0, verbose_name='Оценка фильма')),
                ('movie_actor', models.ManyToManyField(to='movies.Actor', verbose_name='Актеры')),
                ('movie_genre', models.ManyToManyField(to='movies.Genre', verbose_name='Жанр')),
                ('movie_producer', models.ForeignKey(on_delete=models.SET(None), to='movies.producer', verbose_name='Режиссер')),
            ],
        ),
    ]
