# Generated by Django 3.2.5 on 2021-07-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_img',
            field=models.TextField(default='https://xn--90achxr2b.xn--p1ai/files/no_photo3.jpg', verbose_name='Ссылка на обложку'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_trailer',
            field=models.TextField(null=True, verbose_name='Ссылка на трейлер'),
        ),
    ]
