# Generated by Django 3.2.5 on 2021-07-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210704_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_rating',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
